### PR TITLE
1/n Stores IDs are diffrent across DB

### LINKED ISSUE #116: [Regression] Stores IDs are diffrent across DB

### PR DESCRIPTION
**Pull request by deontae-smith**
# Regression Overview
- On Saturday, March 23, 2024, Nexa was alerted to a regression issue detected on the main branch.
- The identified regression led to inconsistencies in IDs across databases, consequently disrupting update operations.

## Regression Source
- The root cause was traced back to the `02-add-store-table.sql` migration file.
- Within this file, the issue arose during the creation of stores, where the utilization of `gen_random_uuid()` resulted in the generation of random IDs without ensuring uniformity or persistence.

## Regression Fix
- To address this issue, a comprehensive fix involved the reconstruction of the store schema.
- IDs are now indexed by migrations and are assigned custom IDs in the format 'Nexa-...' during creation.
- The objective is to maintain uniformity in IDs across databases by virtue of the sequential order in which rows are added.

# Disclaimer
**- This resolution is contingent upon the non-manual manipulation of tables.**

# Requires Verification
**- Reviewers please do-not merge this pull request without validated developer verification.**
- To verify, pull the branch `hotfix/stores-ids`, 
- Start the environment and wait for migrations to run.
- Ensure there is no errors with the migrations
- Ensure you see the updated data in the  `stores.store` table.
- Ensure the ID's are not different.

Please refer to the image below.
Screenshot 2024-03-25 at 3 03 45 PM

## Reference(s)
- Closes #116

### CODE REVIEW

File: apps/frontend/screens/Admin/portal/screen.js [hunk 1]
```diff
@@ -17,6 +17,8 @@ import { useStores } from '@min-two/business-web';
 const AdminPortalScreen = () => {
   const [adminName, setAdminName] = useState('');
   const { allBusiness, pendingBusinesses, verifiedBusinesses } = useStores();
+
+  console.log(verifiedBusinesses, 'bbb');
```
Comment (deontae-smith) [inline apps/frontend/screens/Admin/portal/screen.js:21]: nit: Cleanup
